apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: zif-cm-sample-external-calculation-service
  name: zif-cm-sample-external-calculation-service
spec:
  clusterIP: "None" #Must be headless service for GRPC client-side load-balancing
  selector:
    app.kubernetes.io/name: zif-cm-sample-external-calculation-service