apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zif-cm-sample-external-calculation-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zif-cm-sample-external-calculation-service